use std::{any::Any, collections::BTreeMap};

use crate::button_mapping::{
    ButtonId, CATALOG_VERSION, Mapping, MappingTarget, logical_key_by_symbol,
};
use sha2::{Digest, Sha256};

mod production;
use production::ProductionHwdbSystem;

const GENERATED_MARKER: &str = "# Generated by atvv-bridge; do not edit.\n";
const MATCH_LINE: &str = "evdev:input:b0005v2717p32B8*\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InspectOutcome {
    Ready {
        mapping: Mapping,
        revision: MappingRevision,
    },
    RecoveryRequired,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MappingRevision(String);

impl MappingRevision {
    pub fn from_opaque(value: impl Into<String>) -> Self {
        Self(value.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HwdbMappingError {
    Busy,
    RevisionConflict,
    InconsistentState,
    UnsupportedSystem,
    OperationFailed,
    RollbackFailed,
}

pub struct HwdbMappingHelper {
    system: Box<dyn HwdbSystem>,
}

impl HwdbMappingHelper {
    pub fn production() -> Self {
        Self {
            system: Box::new(ProductionHwdbSystem::host()),
        }
    }

    pub fn inspect(&mut self) -> Result<InspectOutcome, HwdbMappingError> {
        let _lock = self.system.try_lock().map_err(map_system_error)?;
        self.inspect_locked()
    }

    pub fn apply(
        &mut self,
        expected_revision: &MappingRevision,
        mapping: &Mapping,
    ) -> Result<MappingRevision, HwdbMappingError> {
        let _lock = self.system.try_lock().map_err(map_system_error)?;
        let InspectOutcome::Ready { revision, .. } = self.inspect_locked()? else {
            return Err(HwdbMappingError::InconsistentState);
        };
        if &revision != expected_revision {
            return Err(HwdbMappingError::RevisionConflict);
        }

        let prior = self.system.read_managed().map_err(map_system_error)?;
        let candidate = render(mapping);
        let staged = self
            .system
            .stage_candidate(&candidate)
            .map_err(map_system_error)?;
        let properties = self
            .system
            .compile_staged_and_query(staged.as_ref())
            .map_err(map_system_error)?;
        if !properties_match(mapping, &properties) {
            return Err(HwdbMappingError::OperationFailed);
        }
        match self.system.commit_staged(staged) {
            Ok(()) => {}
            Err(SystemError::CommittedButNotDurable) => {
                return self.rollback(prior, HwdbMappingError::OperationFailed);
            }
            Err(error) => return Err(map_system_error(error)),
        }
        if self.system.update_live().is_err() || !self.live_matches(mapping) {
            return self.rollback(prior, HwdbMappingError::OperationFailed);
        }
        Ok(revision_for(Some(&candidate)))
    }

    pub fn reset(&mut self) -> Result<MappingRevision, HwdbMappingError> {
        let _lock = self.system.try_lock().map_err(map_system_error)?;
        self.ensure_supported()?;
        let prior = self.system.read_managed().map_err(map_system_error)?;
        let defaults = Mapping::defaults();
        let properties = self
            .system
            .compile_defaults_and_query()
            .map_err(map_system_error)?;
        if !properties_match(&defaults, &properties) {
            return Err(HwdbMappingError::OperationFailed);
        }
        match self.system.remove_managed() {
            Ok(()) => {}
            Err(SystemError::CommittedButNotDurable) => {
                return self.rollback(prior, HwdbMappingError::OperationFailed);
            }
            Err(error) => return Err(map_system_error(error)),
        }
        if self.system.update_live().is_err() || !self.live_matches(&defaults) {
            return self.rollback(prior, HwdbMappingError::OperationFailed);
        }
        Ok(revision_for(None))
    }

    fn inspect_locked(&mut self) -> Result<InspectOutcome, HwdbMappingError> {
        self.ensure_supported()?;
        let source = self.system.read_managed().map_err(map_system_error)?;
        let mapping = match source.as_deref() {
            Some(source) => match parse(source) {
                Some(mapping) => mapping,
                None => return Ok(InspectOutcome::RecoveryRequired),
            },
            None => Mapping::defaults(),
        };
        if !self.live_matches(&mapping) {
            return Ok(InspectOutcome::RecoveryRequired);
        }
        Ok(InspectOutcome::Ready {
            mapping,
            revision: revision_for(source.as_deref()),
        })
    }

    fn live_matches(&mut self, mapping: &Mapping) -> bool {
        self.system
            .query_live()
            .is_ok_and(|properties| properties_match(mapping, &properties))
    }

    fn ensure_supported(&mut self) -> Result<(), HwdbMappingError> {
        if self.system.is_supported().map_err(map_system_error)? {
            Ok(())
        } else {
            Err(HwdbMappingError::UnsupportedSystem)
        }
    }

    fn rollback(
        &mut self,
        prior: Option<Vec<u8>>,
        recovered_error: HwdbMappingError,
    ) -> Result<MappingRevision, HwdbMappingError> {
        let source_restored = match prior.as_deref() {
            Some(source) => self.system.replace_managed(source),
            None => self.system.remove_managed(),
        };
        if source_restored.is_err() || self.system.update_live().is_err() {
            return Err(HwdbMappingError::RollbackFailed);
        }
        let prior_mapping = match prior.as_deref() {
            Some(source) => parse(source).ok_or(HwdbMappingError::RollbackFailed)?,
            None => Mapping::defaults(),
        };
        if !self.live_matches(&prior_mapping) {
            return Err(HwdbMappingError::RollbackFailed);
        }
        Err(recovered_error)
    }
}

#[derive(Debug, Clone, Copy)]
enum SystemError {
    Busy,
    Unsupported,
    OperationFailed,
    CommittedButNotDurable,
}

fn map_system_error(error: SystemError) -> HwdbMappingError {
    match error {
        SystemError::Busy => HwdbMappingError::Busy,
        SystemError::Unsupported => HwdbMappingError::UnsupportedSystem,
        SystemError::OperationFailed | SystemError::CommittedButNotDurable => {
            HwdbMappingError::OperationFailed
        }
    }
}

trait HwdbSystem {
    fn try_lock(&mut self) -> Result<Box<dyn Any>, SystemError>;
    fn is_supported(&mut self) -> Result<bool, SystemError>;
    fn read_managed(&mut self) -> Result<Option<Vec<u8>>, SystemError>;
    fn stage_candidate(&mut self, source: &[u8]) -> Result<Box<dyn Any>, SystemError>;
    fn compile_staged_and_query(
        &mut self,
        staged: &dyn Any,
    ) -> Result<BTreeMap<String, String>, SystemError>;
    fn compile_defaults_and_query(&mut self) -> Result<BTreeMap<String, String>, SystemError>;
    fn commit_staged(&mut self, staged: Box<dyn Any>) -> Result<(), SystemError>;
    fn replace_managed(&mut self, source: &[u8]) -> Result<(), SystemError>;
    fn remove_managed(&mut self) -> Result<(), SystemError>;
    fn update_live(&mut self) -> Result<(), SystemError>;
    fn query_live(&mut self) -> Result<BTreeMap<String, String>, SystemError>;
}

fn expected_properties(mapping: &Mapping) -> BTreeMap<String, String> {
    mapping
        .iter()
        .filter_map(|(button, target)| {
            let value = hwdb_value(button, target)?;
            Some((format!("KEYBOARD_KEY_{}", button.scan_code()), value))
        })
        .collect()
}

fn hwdb_value(button: ButtonId, target: MappingTarget) -> Option<String> {
    match target {
        MappingTarget::Original if button != ButtonId::Power => None,
        MappingTarget::Original => Some("power".to_owned()),
        MappingTarget::Disabled => Some("reserved".to_owned()),
        MappingTarget::Key(key) => Some(
            key.symbol()
                .strip_prefix("KEY_")
                .expect("registered logical keys use KEY_ names")
                .to_ascii_lowercase(),
        ),
    }
}

fn properties_match(mapping: &Mapping, actual: &BTreeMap<String, String>) -> bool {
    let expected = expected_properties(mapping);
    ButtonId::ALL.into_iter().all(|button| {
        let property = format!("KEYBOARD_KEY_{}", button.scan_code());
        actual.get(&property) == expected.get(&property)
    })
}

fn render(mapping: &Mapping) -> Vec<u8> {
    let mut output =
        format!("{GENERATED_MARKER}# Catalog-Version: {CATALOG_VERSION}\n\n{MATCH_LINE}");
    for button in ButtonId::ALL {
        let target = mapping.get(button);
        let Some(value) = hwdb_value(button, target) else {
            continue;
        };
        output.push_str(&format!(" KEYBOARD_KEY_{}={}\n", button.scan_code(), value));
    }
    output.into_bytes()
}

fn parse(source: &[u8]) -> Option<Mapping> {
    let text = std::str::from_utf8(source).ok()?;
    let prefix = format!("{GENERATED_MARKER}# Catalog-Version: {CATALOG_VERSION}\n\n{MATCH_LINE}");
    let properties = text.strip_prefix(&prefix)?;
    let mut entries: Vec<_> = Mapping::defaults().iter().collect();
    let mut last_index = None;
    for line in properties.lines() {
        let property = line.strip_prefix(" KEYBOARD_KEY_")?;
        let (scan_code, value) = property.split_once('=')?;
        let index = ButtonId::ALL
            .iter()
            .position(|button| button.scan_code() == scan_code)?;
        if last_index.is_some_and(|last| index <= last) {
            return None;
        }
        last_index = Some(index);
        let button = ButtonId::ALL[index];
        let target = match value {
            "power" if button == ButtonId::Power => MappingTarget::Original,
            "reserved" => MappingTarget::Disabled,
            value => {
                let symbol = format!("KEY_{}", value.to_ascii_uppercase());
                MappingTarget::Key(logical_key_by_symbol(&symbol)?)
            }
        };
        entries[index].1 = target;
    }
    let mapping = Mapping::from_entries(entries).ok()?;
    (render(&mapping) == source).then_some(mapping)
}

fn revision_for(source: Option<&[u8]>) -> MappingRevision {
    let mut digest = Sha256::new();
    digest.update(CATALOG_VERSION.to_be_bytes());
    match source {
        None => digest.update([0]),
        Some(source) => {
            digest.update([1]);
            digest.update(source);
        }
    }
    MappingRevision(format!("sha256:{:x}", digest.finalize()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::button_mapping::{MappingTarget, logical_key_by_symbol};
    use std::{cell::RefCell, collections::VecDeque, rc::Rc};

    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    enum Action {
        Lock,
        Supported,
        Read,
        Compile,
        StageCreate,
        StageWrite,
        StagePermissions,
        StageSync,
        Replace,
        Remove,
        Durability,
        Update,
        Query,
    }

    #[derive(Default)]
    struct FakeState {
        source: Option<Vec<u8>>,
        live_source: Option<Vec<u8>>,
        failures: VecDeque<(Action, usize)>,
        busy: bool,
        unsupported: bool,
    }

    struct FakeHwdbSystem {
        state: Rc<RefCell<FakeState>>,
    }

    impl FakeHwdbSystem {
        fn fail(&self, action: Action) -> Result<(), SystemError> {
            let mut state = self.state.borrow_mut();
            let Some((scheduled, skips)) = state.failures.front_mut() else {
                return Ok(());
            };
            if *scheduled == action && *skips > 0 {
                *skips -= 1;
            } else if *scheduled == action {
                state.failures.pop_front();
                return Err(SystemError::OperationFailed);
            }
            Ok(())
        }
    }

    impl HwdbSystem for FakeHwdbSystem {
        fn try_lock(&mut self) -> Result<Box<dyn Any>, SystemError> {
            self.fail(Action::Lock)?;
            if self.state.borrow().busy {
                return Err(SystemError::Busy);
            }
            Ok(Box::new(()))
        }
        fn is_supported(&mut self) -> Result<bool, SystemError> {
            self.fail(Action::Supported)?;
            Ok(!self.state.borrow().unsupported)
        }
        fn read_managed(&mut self) -> Result<Option<Vec<u8>>, SystemError> {
            self.fail(Action::Read)?;
            Ok(self.state.borrow().source.clone())
        }
        fn stage_candidate(&mut self, source: &[u8]) -> Result<Box<dyn Any>, SystemError> {
            self.fail(Action::StageCreate)?;
            self.fail(Action::StageWrite)?;
            self.fail(Action::StagePermissions)?;
            self.fail(Action::StageSync)?;
            Ok(Box::new(source.to_vec()))
        }
        fn compile_staged_and_query(
            &mut self,
            staged: &dyn Any,
        ) -> Result<BTreeMap<String, String>, SystemError> {
            self.fail(Action::Compile)?;
            self.fail(Action::Query)?;
            let source = staged
                .downcast_ref::<Vec<u8>>()
                .ok_or(SystemError::OperationFailed)?;
            let parsed = parse(source);
            parsed
                .map(|mapping| expected_properties(&mapping))
                .ok_or(SystemError::OperationFailed)
        }
        fn compile_defaults_and_query(&mut self) -> Result<BTreeMap<String, String>, SystemError> {
            self.fail(Action::Compile)?;
            self.fail(Action::Query)?;
            Ok(expected_properties(&Mapping::defaults()))
        }
        fn commit_staged(&mut self, staged: Box<dyn Any>) -> Result<(), SystemError> {
            let source = staged
                .downcast::<Vec<u8>>()
                .map_err(|_| SystemError::OperationFailed)?;
            self.replace_managed(&source)
        }
        fn replace_managed(&mut self, source: &[u8]) -> Result<(), SystemError> {
            self.fail(Action::Replace)?;
            self.state.borrow_mut().source = Some(source.to_vec());
            if self.fail(Action::Durability).is_err() {
                return Err(SystemError::CommittedButNotDurable);
            }
            Ok(())
        }
        fn remove_managed(&mut self) -> Result<(), SystemError> {
            self.fail(Action::Remove)?;
            self.state.borrow_mut().source = None;
            if self.fail(Action::Durability).is_err() {
                return Err(SystemError::CommittedButNotDurable);
            }
            Ok(())
        }
        fn update_live(&mut self) -> Result<(), SystemError> {
            self.fail(Action::Update)?;
            let source = self.state.borrow().source.clone();
            self.state.borrow_mut().live_source = source;
            Ok(())
        }
        fn query_live(&mut self) -> Result<BTreeMap<String, String>, SystemError> {
            self.fail(Action::Query)?;
            let live = self
                .state
                .borrow()
                .live_source
                .as_deref()
                .map(parse)
                .unwrap_or_else(|| Some(Mapping::defaults()));
            live.map(|mapping| expected_properties(&mapping))
                .ok_or(SystemError::OperationFailed)
        }
    }

    fn helper() -> (HwdbMappingHelper, Rc<RefCell<FakeState>>) {
        let state = Rc::new(RefCell::new(FakeState::default()));
        let helper = HwdbMappingHelper {
            system: Box::new(FakeHwdbSystem {
                state: state.clone(),
            }),
        };
        (helper, state)
    }

    fn mapping_with_confirm_space() -> Mapping {
        let mut entries: Vec<_> = Mapping::defaults().iter().collect();
        entries[1].1 = MappingTarget::Key(logical_key_by_symbol("KEY_SPACE").unwrap());
        Mapping::from_entries(entries).unwrap()
    }

    #[test]
    fn absent_managed_source_inspects_as_package_defaults() {
        let (mut helper, _) = helper();
        let InspectOutcome::Ready { mapping, revision } = helper.inspect().unwrap() else {
            panic!("package defaults should be trusted");
        };
        assert_eq!(mapping, Mapping::defaults());
        assert!(!revision.as_str().is_empty());
    }

    #[test]
    fn apply_installs_a_complete_mapping_and_changes_the_revision() {
        let (mut helper, _) = helper();
        let InspectOutcome::Ready { revision, .. } = helper.inspect().unwrap() else {
            panic!();
        };
        let mapping = mapping_with_confirm_space();

        let installed_revision = helper.apply(&revision, &mapping).unwrap();

        assert_ne!(installed_revision, revision);
        assert_eq!(
            helper.inspect().unwrap(),
            InspectOutcome::Ready {
                mapping,
                revision: installed_revision,
            }
        );
    }

    #[test]
    fn reset_is_revision_free_and_idempotently_restores_defaults() {
        let (mut helper, _) = helper();
        let first = helper.reset().unwrap();
        let second = helper.reset().unwrap();
        assert_eq!(first, second);
        assert!(matches!(
            helper.inspect().unwrap(),
            InspectOutcome::Ready { mapping, revision }
                if mapping == Mapping::defaults() && revision == second
        ));
    }

    #[test]
    fn canonical_source_is_sparse_ordered_and_uses_hwdb_key_names() {
        let mut entries: Vec<_> = Mapping::defaults().iter().collect();
        entries[0].1 = MappingTarget::Original;
        entries[1].1 = MappingTarget::Key(logical_key_by_symbol("KEY_SPACE").unwrap());
        entries[2].1 = MappingTarget::Disabled;
        let mapping = Mapping::from_entries(entries).unwrap();

        assert_eq!(
            String::from_utf8(render(&mapping)).unwrap(),
            "# Generated by atvv-bridge; do not edit.\n# Catalog-Version: 1\n\nevdev:input:b0005v2717p32B8*\n KEYBOARD_KEY_70066=power\n KEYBOARD_KEY_70028=space\n KEYBOARD_KEY_70052=reserved\n"
        );
    }

    #[test]
    fn revisions_are_opaque_fixed_length_identities_of_presence_content_and_catalog() {
        let absent = revision_for(None);
        let present_empty = revision_for(Some(b""));
        let present_source = revision_for(Some(b"source"));

        assert_eq!(absent.as_str().len(), 71);
        assert_eq!(present_empty.as_str().len(), 71);
        assert_eq!(present_source.as_str().len(), 71);
        assert_ne!(absent, present_empty);
        assert_ne!(present_empty, present_source);
    }

    #[test]
    fn lock_contention_and_missing_capability_fail_without_mutation() {
        for (busy, unsupported, expected) in [
            (true, false, HwdbMappingError::Busy),
            (false, true, HwdbMappingError::UnsupportedSystem),
        ] {
            let (mut helper, state) = helper();
            state.borrow_mut().busy = busy;
            state.borrow_mut().unsupported = unsupported;
            assert_eq!(helper.inspect(), Err(expected));
            assert_eq!(state.borrow().source, None);
        }

        let (mut helper, state) = helper();
        state.borrow_mut().unsupported = true;
        assert_eq!(helper.reset(), Err(HwdbMappingError::UnsupportedSystem));
        assert_eq!(state.borrow().source, None);
    }

    #[test]
    fn revision_conflict_does_not_open_a_write_path() {
        let (mut helper, state) = helper();
        let current = helper.inspect().unwrap();

        assert_eq!(
            helper.apply(
                &MappingRevision("stale".to_owned()),
                &mapping_with_confirm_space()
            ),
            Err(HwdbMappingError::RevisionConflict)
        );
        assert_eq!(helper.inspect().unwrap(), current);
        assert_eq!(state.borrow().source, None);
    }

    #[test]
    fn malformed_source_and_source_database_mismatch_require_recovery() {
        let (mut malformed_helper, malformed) = helper();
        malformed.borrow_mut().source = Some(b"not generated\n".to_vec());
        assert_eq!(
            malformed_helper.inspect(),
            Ok(InspectOutcome::RecoveryRequired)
        );

        let (mut mismatch_helper, mismatch) = helper();
        mismatch.borrow_mut().source = Some(render(&mapping_with_confirm_space()));
        assert_eq!(
            mismatch_helper.inspect(),
            Ok(InspectOutcome::RecoveryRequired)
        );
    }

    #[test]
    fn apply_does_not_depend_on_a_connected_remote() {
        let (mut helper, _) = helper();
        let InspectOutcome::Ready { revision, .. } = helper.inspect().unwrap() else {
            panic!();
        };
        assert!(
            helper
                .apply(&revision, &mapping_with_confirm_space())
                .is_ok()
        );
    }

    #[test]
    fn every_precommit_failure_leaves_source_and_database_unchanged() {
        for action in [
            Action::StageCreate,
            Action::StageWrite,
            Action::StagePermissions,
            Action::StageSync,
            Action::Compile,
            Action::Query,
            Action::Replace,
        ] {
            let (mut helper, state) = helper();
            let InspectOutcome::Ready { revision, .. } = helper.inspect().unwrap() else {
                panic!();
            };
            let before = helper.inspect().unwrap();
            let skips = usize::from(action == Action::Query);
            state.borrow_mut().failures.push_back((action, skips));

            assert_eq!(
                helper.apply(&revision, &mapping_with_confirm_space()),
                Err(HwdbMappingError::OperationFailed)
            );
            assert_eq!(helper.inspect().unwrap(), before);
        }
    }

    #[test]
    fn postcommit_update_and_query_failures_restore_the_prior_state() {
        for action in [Action::Update, Action::Query] {
            let (mut helper, state) = helper();
            let InspectOutcome::Ready { revision, .. } = helper.inspect().unwrap() else {
                panic!();
            };
            let before = helper.inspect().unwrap();
            let skips = usize::from(action == Action::Query);
            state.borrow_mut().failures.push_back((action, skips));

            assert_eq!(
                helper.apply(&revision, &mapping_with_confirm_space()),
                Err(HwdbMappingError::OperationFailed)
            );
            assert_eq!(helper.inspect().unwrap(), before);
        }
    }

    #[test]
    fn a_durability_failure_after_atomic_replace_rolls_back() {
        let (mut helper, state) = helper();
        let InspectOutcome::Ready { revision, .. } = helper.inspect().unwrap() else {
            panic!();
        };
        let before = helper.inspect().unwrap();
        state
            .borrow_mut()
            .failures
            .push_back((Action::Durability, 0));

        assert_eq!(
            helper.apply(&revision, &mapping_with_confirm_space()),
            Err(HwdbMappingError::OperationFailed)
        );
        assert_eq!(helper.inspect().unwrap(), before);
    }

    #[test]
    fn reset_failures_restore_the_installed_mapping() {
        for action in [Action::Durability, Action::Update, Action::Query] {
            let (mut helper, state) = helper();
            let source = render(&mapping_with_confirm_space());
            state.borrow_mut().source = Some(source.clone());
            state.borrow_mut().live_source = Some(source.clone());
            let before = helper.inspect().unwrap();
            let skips = usize::from(action == Action::Query);
            state.borrow_mut().failures.push_back((action, skips));

            assert_eq!(helper.reset(), Err(HwdbMappingError::OperationFailed));
            assert_eq!(helper.inspect().unwrap(), before);
        }
    }

    #[test]
    fn reset_precommit_failures_leave_the_installed_mapping_unchanged() {
        for action in [Action::Compile, Action::Query, Action::Remove] {
            let (mut helper, state) = helper();
            let source = render(&mapping_with_confirm_space());
            state.borrow_mut().source = Some(source.clone());
            state.borrow_mut().live_source = Some(source.clone());
            let before = helper.inspect().unwrap();
            state.borrow_mut().failures.push_back((action, 0));

            assert_eq!(helper.reset(), Err(HwdbMappingError::OperationFailed));
            assert_eq!(helper.inspect().unwrap(), before);
        }
    }

    #[test]
    fn rollback_failures_report_that_consistency_could_not_be_restored() {
        for failures in [
            vec![Action::Update, Action::Remove],
            vec![Action::Update, Action::Update],
            vec![Action::Update, Action::Query],
        ] {
            let (mut helper, state) = helper();
            let InspectOutcome::Ready { revision, .. } = helper.inspect().unwrap() else {
                panic!();
            };
            state
                .borrow_mut()
                .failures
                .extend(failures.into_iter().map(|action| (action, 0)));

            assert_eq!(
                helper.apply(&revision, &mapping_with_confirm_space()),
                Err(HwdbMappingError::RollbackFailed)
            );
        }
    }

    #[test]
    fn rollback_failure_injection_covers_restoring_an_existing_source() {
        for rollback_failure in [Action::Replace, Action::Durability] {
            let (mut helper, state) = helper();
            let prior_source = render(&mapping_with_confirm_space());
            state.borrow_mut().source = Some(prior_source.clone());
            state.borrow_mut().live_source = Some(prior_source);
            let InspectOutcome::Ready { revision, .. } = helper.inspect().unwrap() else {
                panic!();
            };
            state
                .borrow_mut()
                .failures
                .extend([(Action::Update, 0), (rollback_failure, 0)]);

            assert_eq!(
                helper.apply(&revision, &Mapping::defaults()),
                Err(HwdbMappingError::RollbackFailed)
            );
        }
    }

    #[test]
    fn reset_is_the_recovery_operation_for_malformed_source() {
        let (mut helper, state) = helper();
        state.borrow_mut().source = Some(b"not generated\n".to_vec());

        assert!(helper.reset().is_ok());
        assert!(matches!(
            helper.inspect().unwrap(),
            InspectOutcome::Ready { mapping, .. } if mapping == Mapping::defaults()
        ));
    }

    #[test]
    fn failed_reset_from_untrusted_source_reports_failed_consistency_recovery() {
        let (mut helper, state) = helper();
        state.borrow_mut().source = Some(b"not generated\n".to_vec());
        state.borrow_mut().failures.push_back((Action::Update, 0));

        assert_eq!(helper.reset(), Err(HwdbMappingError::RollbackFailed));
    }
}
